Slon gleda leva.
Slon gleda psa.
Slon gleda muco.
Slon gleda tigra.
Slon gleda ribo.
Slon gleda zajca.
Slon lovi leva.
Slon lovi psa.
Slon lovi muco.
Slon lovi tigra.
Slon lovi ribo.
Slon lovi zajca.
Slon hrani leva.
Slon hrani psa.
Slon hrani muco.
Slon hrani tigra.
Slon hrani ribo.
Slon hrani zajca.
Slon vidi leva.
Slon vidi psa.
Slon vidi muco.
Slon vidi tigra.
Slon vidi ribo.
Slon vidi zajca.
Slon prebuja leva.
Slon prebuja psa.
Slon prebuja muco.
Slon prebuja tigra.
Slon prebuja ribo.
Slon prebuja zajca.
Slon pozdravlja leva.
Slon pozdravlja psa.
Slon pozdravlja muco.
Slon pozdravlja tigra.
Slon pozdravlja ribo.
Slon pozdravlja zajca.
Slon objema leva.
Slon objema psa.
Slon objema muco.
Slon objema tigra.
Slon objema ribo.
Slon objema zajca.
Lev gleda psa.
Lev gleda muco.
Lev gleda tigra.
Lev gleda ribo.
Lev gleda zajca.
Lev lovi psa.
Lev lovi muco.
Lev lovi tigra.
Lev lovi ribo.
Lev lovi zajca.
Lev hrani psa.
Lev hrani muco.
Lev hrani tigra.
Lev hrani ribo.
Lev hrani zajca.
Lev vidi psa.
Lev vidi muco.
Lev vidi tigra.
Lev vidi ribo.
Lev vidi zajca.
Lev prebuja psa.
Lev prebuja muco.
Lev prebuja tigra.
Lev prebuja ribo.
Lev prebuja zajca.
Lev pozdravlja psa.
Lev pozdravlja muco.
Lev pozdravlja tigra.
Lev pozdravlja ribo.
Lev pozdravlja zajca.
Lev objema psa.
Lev objema muco.
Lev objema tigra.
Lev objema ribo.
Lev objema zajca.
Pes gleda muco.
Pes gleda tigra.
Pes gleda ribo.
Pes gleda zajca.
Pes lovi muco.
Pes lovi tigra.
Pes lovi ribo.
Pes lovi zajca.
Pes hrani muco.
Pes hrani tigra.
Pes hrani ribo.
Pes hrani zajca.
Pes vidi muco.
Pes vidi tigra.
Pes vidi ribo.
Pes vidi zajca.
Pes prebuja muco.
Pes prebuja tigra.
Pes prebuja ribo.
Pes prebuja zajca.
Pes pozdravlja muco.
Pes pozdravlja tigra.
Pes pozdravlja ribo.
Pes pozdravlja zajca.
Pes objema muco.
Pes objema tigra.
Pes objema ribo.
Pes objema zajca.
Muca gleda tigra.
Muca gleda ribo.
Muca gleda zajca.
Muca lovi tigra.
Muca lovi ribo.
Muca lovi zajca.
Muca hrani tigra.
Muca hrani ribo.
Muca hrani zajca.
Muca vidi tigra.
Muca vidi ribo.
Muca vidi zajca.
Muca prebuja tigra.
Muca prebuja ribo.
Muca prebuja zajca.
Muca pozdravlja tigra.
Muca pozdravlja ribo.
Muca pozdravlja zajca.
Muca objema tigra.
Muca objema ribo.
Muca objema zajca.
Tiger gleda ribo.
Tiger gleda zajca.
Tiger lovi ribo.
Tiger lovi zajca.
Tiger hrani ribo.
Tiger hrani zajca.
Tiger vidi ribo.
Tiger vidi zajca.
Tiger prebuja ribo.
Tiger prebuja zajca.
Tiger pozdravlja ribo.
Tiger pozdravlja zajca.
Tiger objema ribo.
Tiger objema zajca.
Riba gleda zajca.
Riba lovi zajca.
Riba hrani zajca.
Riba vidi zajca.
Riba prebuja zajca.
Riba pozdravlja zajca.
Riba objema zajca.
