Jazbec vidi medveda.
Jazbec vidi srno.
Jazbec vidi netopirja.
Jazbec vidi krta.
Jazbec vidi pujsa.
Jazbec vidi kuro.
Jazbec gleda medveda.
Jazbec gleda srno.
Jazbec gleda netopirja.
Jazbec gleda krta.
Jazbec gleda pujsa.
Jazbec gleda kuro.
Jazbec opazuje medveda.
Jazbec opazuje srno.
Jazbec opazuje netopirja.
Jazbec opazuje krta.
Jazbec opazuje pujsa.
Jazbec opazuje kuro.
Jazbec hrani medveda.
Jazbec hrani srno.
Jazbec hrani netopirja.
Jazbec hrani krta.
Jazbec hrani pujsa.
Jazbec hrani kuro.
Jazbec nagovarja medveda.
Jazbec nagovarja srno.
Jazbec nagovarja netopirja.
Jazbec nagovarja krta.
Jazbec nagovarja pujsa.
Jazbec nagovarja kuro.
Jazbec razume medveda.
Jazbec razume srno.
Jazbec razume netopirja.
Jazbec razume krta.
Jazbec razume pujsa.
Jazbec razume kuro.
Jazbec opozarja medveda.
Jazbec opozarja srno.
Jazbec opozarja netopirja.
Jazbec opozarja krta.
Jazbec opozarja pujsa.
Jazbec opozarja kuro.
Medved vidi srno.
Medved vidi netopirja.
Medved vidi krta.
Medved vidi pujsa.
Medved vidi kuro.
Medved gleda srno.
Medved gleda netopirja.
Medved gleda krta.
Medved gleda pujsa.
Medved gleda kuro.
Medved opazuje srno.
Medved opazuje netopirja.
Medved opazuje krta.
Medved opazuje pujsa.
Medved opazuje kuro.
Medved hrani srno.
Medved hrani netopirja.
Medved hrani krta.
Medved hrani pujsa.
Medved hrani kuro.
Medved nagovarja srno.
Medved nagovarja netopirja.
Medved nagovarja krta.
Medved nagovarja pujsa.
Medved nagovarja kuro.
Medved razume srno.
Medved razume netopirja.
Medved razume krta.
Medved razume pujsa.
Medved razume kuro.
Medved opozarja srno.
Medved opozarja netopirja.
Medved opozarja krta.
Medved opozarja pujsa.
Medved opozarja kuro.
Srna vidi netopirja.
Srna vidi krta.
Srna vidi pujsa.
Srna vidi kuro.
Srna gleda netopirja.
Srna gleda krta.
Srna gleda pujsa.
Srna gleda kuro.
Srna opazuje netopirja.
Srna opazuje krta.
Srna opazuje pujsa.
Srna opazuje kuro.
Srna hrani netopirja.
Srna hrani krta.
Srna hrani pujsa.
Srna hrani kuro.
Srna nagovarja netopirja.
Srna nagovarja krta.
Srna nagovarja pujsa.
Srna nagovarja kuro.
Srna razume netopirja.
Srna razume krta.
Srna razume pujsa.
Srna razume kuro.
Srna opozarja netopirja.
Srna opozarja krta.
Srna opozarja pujsa.
Srna opozarja kuro.
Netopir vidi krta.
Netopir vidi pujsa.
Netopir vidi kuro.
Netopir gleda krta.
Netopir gleda pujsa.
Netopir gleda kuro.
Netopir opazuje krta.
Netopir opazuje pujsa.
Netopir opazuje kuro.
Netopir hrani krta.
Netopir hrani pujsa.
Netopir hrani kuro.
Netopir nagovarja krta.
Netopir nagovarja pujsa.
Netopir nagovarja kuro.
Netopir razume krta.
Netopir razume pujsa.
Netopir razume kuro.
Netopir opozarja krta.
Netopir opozarja pujsa.
Netopir opozarja kuro.
Krt vidi pujsa.
Krt vidi kuro.
Krt gleda pujsa.
Krt gleda kuro.
Krt opazuje pujsa.
Krt opazuje kuro.
Krt hrani pujsa.
Krt hrani kuro.
Krt nagovarja pujsa.
Krt nagovarja kuro.
Krt razume pujsa.
Krt razume kuro.
Krt opozarja pujsa.
Krt opozarja kuro.
Pujs vidi kuro.
Pujs gleda kuro.
Pujs opazuje kuro.
Pujs hrani kuro.
Pujs nagovarja kuro.
Pujs razume kuro.
Pujs opozarja kuro.
