Slon gleda leva.
Slon gleda psa.
Slon gleda muco.
Slon gleda tigra.
Slon gleda ribo.
Slon lovi leva.
Slon lovi psa.
Slon lovi muco.
Slon lovi tigra.
Slon lovi ribo.
Slon hrani leva.
Slon hrani psa.
Slon hrani muco.
Slon hrani tigra.
Slon hrani ribo.
Slon vidi leva.
Slon vidi psa.
Slon vidi muco.
Slon vidi tigra.
Slon vidi ribo.
Slon nadzira leva.
Slon nadzira psa.
Slon nadzira muco.
Slon nadzira tigra.
Slon nadzira ribo.
Slon prebuja leva.
Slon prebuja psa.
Slon prebuja muco.
Slon prebuja tigra.
Slon prebuja ribo.
Slon pozdravlja leva.
Slon pozdravlja psa.
Slon pozdravlja muco.
Slon pozdravlja tigra.
Slon pozdravlja ribo.
Lev gleda psa.
Lev gleda muco.
Lev gleda tigra.
Lev gleda ribo.
Lev lovi psa.
Lev lovi muco.
Lev lovi tigra.
Lev lovi ribo.
Lev hrani psa.
Lev hrani muco.
Lev hrani tigra.
Lev hrani ribo.
Lev vidi psa.
Lev vidi muco.
Lev vidi tigra.
Lev vidi ribo.
Lev nadzira psa.
Lev nadzira muco.
Lev nadzira tigra.
Lev nadzira ribo.
Lev prebuja psa.
Lev prebuja muco.
Lev prebuja tigra.
Lev prebuja ribo.
Lev pozdravlja psa.
Lev pozdravlja muco.
Lev pozdravlja tigra.
Lev pozdravlja ribo.
Pes gleda muco.
Pes gleda tigra.
Pes gleda ribo.
Pes lovi muco.
Pes lovi tigra.
Pes lovi ribo.
Pes hrani muco.
Pes hrani tigra.
Pes hrani ribo.
Pes vidi muco.
Pes vidi tigra.
Pes vidi ribo.
Pes nadzira muco.
Pes nadzira tigra.
Pes nadzira ribo.
Pes prebuja muco.
Pes prebuja tigra.
Pes prebuja ribo.
Pes pozdravlja muco.
Pes pozdravlja tigra.
Pes pozdravlja ribo.
Muca gleda tigra.
Muca gleda ribo.
Muca lovi tigra.
Muca lovi ribo.
Muca hrani tigra.
Muca hrani ribo.
Muca vidi tigra.
Muca vidi ribo.
Muca nadzira tigra.
Muca nadzira ribo.
Muca prebuja tigra.
Muca prebuja ribo.
Muca pozdravlja tigra.
Muca pozdravlja ribo.
Tiger gleda ribo.
Tiger lovi ribo.
Tiger hrani ribo.
Tiger vidi ribo.
Tiger nadzira ribo.
Tiger prebuja ribo.
Tiger pozdravlja ribo.
