Medved razume srno.
Medved razume lisico.
Medved razume jelena.
Medved opozarja srno.
Medved opozarja lisico.
Medved opozarja jelena.
Medved preganja srno.
Medved preganja lisico.
Medved preganja jelena.
Srna razume lisico.
Srna razume jelena.
Srna opozarja lisico.
Srna opozarja jelena.
Srna preganja lisico.
Srna preganja jelena.
Lisica razume jelena.
Lisica opozarja jelena.
Lisica preganja jelena.
